// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdG0quqGBmJcbPMXqFiA08a8ubKD2tdJI',
    appId: '1:1028003347003:web:c7966e36003e1f243bfa1e',
    messagingSenderId: '1028003347003',
    projectId: 'bandasybandassg',
    authDomain: 'bandasybandassg.firebaseapp.com',
    storageBucket: 'bandasybandassg.firebasestorage.app',
    measurementId: 'G-LTD1LGZ0NL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4dZJ-UsvHlgGrBkXixCJLCtOOx3zxNPM',
    appId: '1:1028003347003:android:1122312f608f58f33bfa1e',
    messagingSenderId: '1028003347003',
    projectId: 'bandasybandassg',
    storageBucket: 'bandasybandassg.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDg_8Krb4gYCCb2PTnyt5rBHlYRNrEpOa4',
    appId: '1:1028003347003:ios:cd92d61731dd2ba23bfa1e',
    messagingSenderId: '1028003347003',
    projectId: 'bandasybandassg',
    storageBucket: 'bandasybandassg.firebasestorage.app',
    iosBundleId: 'com.example.bandasybandas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDg_8Krb4gYCCb2PTnyt5rBHlYRNrEpOa4',
    appId: '1:1028003347003:ios:cd92d61731dd2ba23bfa1e',
    messagingSenderId: '1028003347003',
    projectId: 'bandasybandassg',
    storageBucket: 'bandasybandassg.firebasestorage.app',
    iosBundleId: 'com.example.bandasybandas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdG0quqGBmJcbPMXqFiA08a8ubKD2tdJI',
    appId: '1:1028003347003:web:006b94731866d8cc3bfa1e',
    messagingSenderId: '1028003347003',
    projectId: 'bandasybandassg',
    authDomain: 'bandasybandassg.firebaseapp.com',
    storageBucket: 'bandasybandassg.firebasestorage.app',
    measurementId: 'G-8WP7XMCTW5',
  );
}
